apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: wokibrain-ingress
  namespace: wokibrain
  annotations:
    kubernetes.io/ingress.class: 'nginx'
    cert-manager.io/cluster-issuer: 'letsencrypt-prod'
    nginx.ingress.kubernetes.io/ssl-redirect: 'true'
    nginx.ingress.kubernetes.io/rate-limit: '100'
    nginx.ingress.kubernetes.io/limit-rps: '100'
    nginx.ingress.kubernetes.io/proxy-body-size: '10m'
    nginx.ingress.kubernetes.io/proxy-connect-timeout: '60'
    nginx.ingress.kubernetes.io/proxy-send-timeout: '60'
    nginx.ingress.kubernetes.io/proxy-read-timeout: '60'
spec:
  tls:
    - hosts:
        - api.wokibrain.grgcrew.com
      secretName: wokibrain-tls
  rules:
    - host: api.wokibrain.grgcrew.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: wokibrain-api
                port:
                  number: 80
