apiVersion: v1
kind: Secret
metadata:
  name: wokibrain-secrets
  namespace: wokibrain
type: Opaque
stringData:
  mongodb-uri: 'mongodb://admin:CHANGE_ME@wokibrain-mongodb:27017/wokibrain?authSource=admin'
  jwt-access-secret: 'CHANGE_ME_ACCESS_SECRET'
  jwt-refresh-secret: 'CHANGE_ME_REFRESH_SECRET'
  redis-password: ''
  api-master-key: 'CHANGE_ME_MASTER_KEY'


